/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Caja;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JPanel;
import vista.TemaManager;

/**
 *
 * @author ADSO
 */
public class Caja extends javax.swing.JPanel {

    /**
     * Creates new form caja
     */
    public Caja() {
        initComponents();
        mostrarIngresos();
        aplicarTema();
        TemaManager.getInstance().addThemeChangeListener(() -> {
            aplicarTema(); // Update theme when it changes
        });
    }

    public void aplicarTema() {
        boolean oscuro = TemaManager.getInstance().isOscuro();

        if (oscuro) {
            // Configuración para modo oscuro
            Color fondo = new Color(21, 21, 33);
            Color fondoTabla = new Color(30, 30, 45);
            Color encabezado = new Color(67, 71, 120);
            Color texto = Color.WHITE;

            // Panel principal
            contenedorPrincipal.setBackground(fondo);
            panelP1.setBackground(fondo);

            // Botones
            btnIngresos.setBackground(encabezado);
            btnIngresos.setBackgroundHover(new Color(118, 142, 240));
            btnEgresos2.setBackground(encabezado);
            btnEgresos2.setBackgroundHover(new Color(118, 142, 240));

        } else {
            Color fondo = new Color(242, 247, 255);
            Color texto = Color.BLACK;
            Color primario = new Color(72, 92, 188);

            contenedorPrincipal.setBackground(fondo);
            panelP1.setBackground(fondo);

            /*
            Tabla1.setBackground(new Color(255, 255, 255));
            Tabla1.setBackgoundHead(new Color(46, 49, 82));
            Tabla1.setForegroundHead(Color.WHITE);
            Tabla1.setBackgoundHover(new Color(67, 150, 209));
            Tabla1.setFont(new Font("Tahoma", Font.PLAIN, 15));
            Tabla1.setColorPrimary(new Color(242, 242, 242));
            Tabla1.setColorPrimaryText(texto);
            Tabla1.setColorSecondary(new Color(255, 255, 255));
            Tabla1.setColorSecundaryText(texto);
            Tabla1.setColorBorderHead(primario);
            Tabla1.setColorBorderRows(new Color(0, 0, 0));
            Tabla1.setFontHead(new Font("Tahoma", Font.BOLD, 15));
            Tabla1.setFontRowHover(new Font("Tahoma", Font.BOLD, 15));
            Tabla1.setFontRowSelect(new Font("Tahoma", Font.BOLD, 15));
            Tabla1.setEffectHover(true);
            Tabla1.setSelectionBackground(new Color(67, 150, 209));
            Tabla1.setShowGrid(true);
            Tabla1.setGridColor(Color.WHITE); // o el color que desees
            Tabla1.setBackground(Color.WHITE);
            Tabla1.setColorPrimary(new Color(242, 242, 242)); // Fondo filas impares
            Tabla1.setColorSecondary(Color.WHITE); // Fondo filas pares
            Tabla1.setForeground(Color.BLACK);*/
            btnIngresos.setBackground(new Color(46, 49, 82));
            btnEgresos2.setBackground(new Color(46, 49, 82));

        }

    }

    private void mostrarIngresos() {
        if (!this.btnIngresos.isSelected()) {
            this.btnIngresos.setSelected(true);
            this.btnEgresos2.setSelected(false);

            ingresos es = new ingresos(panelP1);
            es.setSize(1260, 730);
            es.setLocation(0, 0);

            panelP1.removeAll();
            panelP1.add(es);
            panelP1.revalidate();
            panelP1.repaint();
        }
    }

    private void mostrarEgresos() {
        if (!this.btnEgresos2.isSelected()) {
            this.btnIngresos.setSelected(false);
            this.btnEgresos2.setSelected(true);

            Egresos as = new Egresos();
            as.setSize(1260, 730);
            as.setLocation(0, 0);

            panelP1.removeAll();
            panelP1.add(as);
            panelP1.revalidate();
            panelP1.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorPrincipal = new javax.swing.JPanel();
        btnEgresos2 = new RSMaterialComponent.RSButtonShapeIcon();
        btnIngresos = new RSMaterialComponent.RSButtonShapeIcon();
        panelP1 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1290, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedorPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        contenedorPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEgresos2.setBackground(new java.awt.Color(0, 0, 0));
        btnEgresos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wrench.png"))); // NOI18N
        btnEgresos2.setText("Egresos");
        btnEgresos2.setBackgroundHover(new java.awt.Color(102, 102, 102));
        btnEgresos2.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        btnEgresos2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MONEY_OFF);
        btnEgresos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEgresos2ActionPerformed(evt);
            }
        });
        contenedorPrincipal.add(btnEgresos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 168, -1));

        btnIngresos.setBackground(new java.awt.Color(0, 0, 0));
        btnIngresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus (1).png"))); // NOI18N
        btnIngresos.setText("Ingresos");
        btnIngresos.setBackgroundHover(new java.awt.Color(102, 102, 102));
        btnIngresos.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        btnIngresos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MONETIZATION_ON);
        btnIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosActionPerformed(evt);
            }
        });
        contenedorPrincipal.add(btnIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 177, -1));

        panelP1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelP1Layout = new javax.swing.GroupLayout(panelP1);
        panelP1.setLayout(panelP1Layout);
        panelP1Layout.setHorizontalGroup(
            panelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
        );
        panelP1Layout.setVerticalGroup(
            panelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        contenedorPrincipal.add(panelP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1350, 600));

        add(contenedorPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 730));
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosActionPerformed
        mostrarIngresos();
    }//GEN-LAST:event_btnIngresosActionPerformed

    private void btnEgresos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEgresos2ActionPerformed
        mostrarEgresos();
    }//GEN-LAST:event_btnEgresos2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonShapeIcon btnEgresos2;
    private RSMaterialComponent.RSButtonShapeIcon btnIngresos;
    private javax.swing.JPanel contenedorPrincipal;
    private javax.swing.JPanel panelP1;
    // End of variables declaration//GEN-END:variables

}
