/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.Caja;

import java.awt.Frame;
import java.awt.image.BufferedImage;

/**
 *
 * @author EQUIPO
 */
public class DetalleEgreso extends javax.swing.JDialog {

    /**
     * Creates new form DetallleEtapa
     */
    public DetalleEgreso(Frame parent, boolean modal, int idEgreso, String fecha, String descripcion, String categoria, String monto, String proveedor, String productos, String cantidad) {
        super(parent, modal);
        initComponents();
        setIconImage(new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB_PRE));

        // Asignar los valores a los componentes con manejo de nulos
        ID.setText(String.valueOf(idEgreso));
        fecha_pago.setText(fecha != null ? fecha : "No especificado");
        txtdescripcion.setText(descripcion != null ? descripcion : "No especificado");
        txtcategoria.setText(categoria != null ? categoria : "No especificado");
        cantidadValor.setText(monto != null ? monto : "No especificado");
        txtcaidad.setText(String.valueOf(cantidad));

        // Ajustar el texto para que use múltiples líneas si es necesario
        txtdescripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        // Centrar el diálogo
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fecha_pago = new javax.swing.JLabel();
        txtcategoria = new javax.swing.JLabel();
        cantidadValor = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar1 = new rojeru_san.RSButtonRiple();
        txtcaidad = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Codigo:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        fecha_pago.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fecha_pago.setForeground(new java.awt.Color(0, 0, 0));
        fecha_pago.setText("fecha_pago");
        jPanel2.add(fecha_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        txtcategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcategoria.setForeground(new java.awt.Color(0, 0, 0));
        txtcategoria.setText("categoria");
        jPanel2.add(txtcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        cantidadValor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidadValor.setForeground(new java.awt.Color(0, 0, 0));
        cantidadValor.setText("cantidad");
        jPanel2.add(cantidadValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        txtdescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtdescripcion.setForeground(new java.awt.Color(0, 0, 0));
        txtdescripcion.setText("descripcion");
        jPanel2.add(txtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        ID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(0, 0, 0));
        ID.setText("ID");
        jPanel2.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Categoria:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Monto:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Descripcion:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Fecha del pago: ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jPanel4.setBackground(new java.awt.Color(46, 49, 82));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century751 BT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Detalle Egreso");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnGuardar1.setBackground(new java.awt.Color(46, 49, 82));
        btnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x (1).png"))); // NOI18N
        btnGuardar1.setColorHover(new java.awt.Color(204, 0, 0));
        btnGuardar1.setFont(new java.awt.Font("Humnst777 BlkCn BT", 1, 18)); // NOI18N
        btnGuardar1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 30, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 50));

        txtcaidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcaidad.setForeground(new java.awt.Color(0, 0, 0));
        txtcaidad.setText("cantidad");
        jPanel2.add(txtcaidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Cantidad:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        this.dispose();

    }//GEN-LAST:event_btnGuardar1ActionPerformed

    /**
     * @param args the command line arguments
     *
     *
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private rojeru_san.RSButtonRiple btnGuardar1;
    private javax.swing.JLabel cantidadValor;
    private javax.swing.JLabel fecha_pago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel txtcaidad;
    private javax.swing.JLabel txtcategoria;
    private javax.swing.JLabel txtdescripcion;
    // End of variables declaration//GEN-END:variables
}
