/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.Caja;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author ZenBook
 */
public class iAbonoNuevo extends javax.swing.JDialog {

    private String[] datos; // Almacena los datos ingresados
    private boolean guardado = false; // Indica si se presionó "Guardar"
    private javax.swing.JSpinner spinnerImporte;

    /**
     * Creates new form iAbonoNuevo
     */
    public iAbonoNuevo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        ((AbstractDocument) txtImporte.getDocument()).setDocumentFilter(new NumberFormatFilter());

// Agrega este KeyListener al txtImporte:
        txtImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formatNumberField();
            }
        });

    }

    private void formatNumberField() {
        // Eliminar todas las comas existentes para procesar el número limpio
        String text = txtImporte.getText().replaceAll("[^0-9]", "");

        if (!text.isEmpty()) {
            try {
                long amount = Long.parseLong(text);
                // Formatear con comas como separadores de miles
                String formatted = String.format("%,d", amount)
                        .replace(",", "X") // Marcador temporal
                        .replace(".", ",") // Cambiar puntos por comas (si el locale usa puntos)
                        .replace("X", ","); // Restaurar comas de miles

                // Solo actualizar si el formato cambió (para evitar bucles)
                if (!formatted.equals(txtImporte.getText())) {
                    txtImporte.setText(formatted);
                    // Mover el cursor al final
                    txtImporte.setCaretPosition(formatted.length());
                }
            } catch (NumberFormatException e) {
                // No hacer nada si no es número válido
            }
        }
    }

    public String[] getDatos() {
        return datos;
    }

    // Método para verificar si se presionó "Guardar"
    public boolean isGuardado() {
        return guardado;
    }

    // Métodos getter para acceder a los datos
    public Date getFecha() {
        return dateFecha.getDate();
    }

    public String getImporte() {
        return txtImporte.getText().replace(",", "").trim();
    }

    public String getMetodoPago() {
        return (String) cmbMetodo.getSelectedItem();
    }

    public void setFecha(Date fecha) {
        dateFecha.setDate(fecha);
    }

    public void setImporte(String importe) {
        txtImporte.setText(importe);
    }

    public void setMetodoPago(String metodo) {
        cmbMetodo.setSelectedItem(metodo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roboto1 = new efectos.Roboto();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dateFecha = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbMetodo = new RSMaterialComponent.RSComboBoxMaterial();
        btnGuardar = new RSMaterialComponent.RSButtonShape();
        btnSalir1 = new rojeru_san.RSButton();
        txtImporte = new RSMaterialComponent.RSTextFieldOne();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Metodo de pago:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        dateFecha.setBackground(new java.awt.Color(255, 255, 255));
        dateFecha.setToolTipText("");
        jPanel1.add(dateFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 200, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Fecha:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Importe:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        cmbMetodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione metodo de pago:", "Efectivo", "Transferencia Bancaria", "Tarjeta de Crédito" }));
        cmbMetodo.setColorMaterial(new java.awt.Color(0, 0, 0));
        cmbMetodo.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        cmbMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMetodoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 200, 30));

        btnGuardar.setBackground(new java.awt.Color(46, 49, 82));
        btnGuardar.setText("Guardar");
        btnGuardar.setBackgroundHover(new java.awt.Color(0, 135, 0));
        btnGuardar.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        btnGuardar.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 97, 28));

        btnSalir1.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x (3).png"))); // NOI18N
        btnSalir1.setColorHover(new java.awt.Color(211, 0, 52));
        btnSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalir1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalir1MouseExited(evt);
            }
        });
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 2, 27, 22));

        txtImporte.setForeground(new java.awt.Color(0, 0, 0));
        txtImporte.setBorderColor(new java.awt.Color(204, 204, 204));
        txtImporte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtImporte.setPhColor(new java.awt.Color(204, 204, 204));
        txtImporte.setPlaceholder("");
        txtImporte.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtImporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtImporteMouseClicked(evt);
            }
        });
        txtImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtImporteKeyPressed(evt);
            }
        });
        jPanel1.add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 200, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 266, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void cmbMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMetodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMetodoActionPerformed

    private void btnSalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1MouseClicked

    private void btnSalir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir1MouseEntered
        btnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x (1).png")));

    }//GEN-LAST:event_btnSalir1MouseEntered

    private void btnSalir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir1MouseExited
        btnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x (3).png")));        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1MouseExited

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        guardado = false;
        setVisible(false); // Cerrar el diálogo
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Validación de campos
        if (dateFecha.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione la fecha", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Eliminar comas para validación numérica
        String importeText = txtImporte.getText().replace(",", "");
        if (importeText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el importe", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Long.parseLong(importeText); // Usamos Long en lugar de Double
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Importe debe ser numérico", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (cmbMetodo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un método de pago", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        guardado = true;
        dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtImporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtImporteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImporteMouseClicked

    private void txtImporteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImporteKeyPressed

    }//GEN-LAST:event_txtImporteKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iAbonoNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iAbonoNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iAbonoNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iAbonoNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                iAbonoNuevo dialog = new iAbonoNuevo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonShape btnGuardar;
    private rojeru_san.RSButton btnSalir1;
    private RSMaterialComponent.RSComboBoxMaterial cmbMetodo;
    private com.toedter.calendar.JDateChooser dateFecha;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private efectos.Roboto roboto1;
    private RSMaterialComponent.RSTextFieldOne txtImporte;
    // End of variables declaration//GEN-END:variables

}
