/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

//import controlador.Contrl_login;
import vista.alertas.CodigoIncorrectoAlerta;
import vista.alertas.ReeenvioCodigoAlerta;
import vista.alertas.ValidacionCodigoExitoso;
import java.awt.BorderLayout;
import java.awt.Frame;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import javax.swing.Timer;
import modelo.Consulta_Usuarios;

public class Contrasena3 extends javax.swing.JFrame {

    Consulta_Usuarios consulta = new Consulta_Usuarios();
    private String correoIngresado;
    private javax.swing.JLabel jLabelTimer;
    private Timer activeTimer = null;// Nuevo JLabel para mostrar el temporizador

    public void setCorreoIngresado(String correo) {
        this.correoIngresado = correo;
    }

    public Contrasena3() {
        initComponents();
txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
    @Override
    public void keyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || txtcodigo.getText().length() >= 6) {
            evt.consume(); // Bloquea si no es número o si ya hay 6 caracteres
        }
    }
});

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);

        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.CENTER;
        add(kGradientPanel1, gbc);

        JPanel fondo = new JPanel(new BorderLayout());
        fondo.add(kGradientPanel1, BorderLayout.CENTER);
        setContentPane(fondo);
        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel6.setText("Reenviar codigo");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 120, -1));

// Agregar el JLabel para el temporizador
// Agregar el JLabel para el temporizador
// In the Contrasena3 constructor
        jLabelTimer = new javax.swing.JLabel();
        jLabelTimer.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabelTimer.setForeground(new java.awt.Color(255, 0, 0)); // Red color
        jLabelTimer.setText("30s"); // Valor inicial
        jLabelTimer.setVisible(false); // Oculto inicialmente
        jPanel6.add(jLabelTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 50, -1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel6 = new javax.swing.JPanel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        txtcodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(239, 248, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(254, 254, 254));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/logo_azul.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel6.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 90, 90));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel11.setText("Revisa tu bandeja de entrada");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel7.setText("Codigo");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 60, 30));

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(29, 30, 51));
        rSMaterialButtonRectangle2.setText("Siguiente ");
        rSMaterialButtonRectangle2.setActionCommand("Siguiente->");
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });
        jPanel6.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 420, 50));

        txtcodigo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        jPanel6.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 410, 40));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel8.setText("Introducir otra direccion de correo electronico");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, 30));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel9.setText("Ingresa el codigo de 6 digitos que te hemos enviado a ");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 410, 20));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel10.setText("tu correo electronico");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 410, 20));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel6.setText("Reenviar codigo");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 120, -1));

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 17)); // NOI18N
        jLabel13.setText("correos no deseados");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 170, 20));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 17)); // NOI18N
        jLabel14.setText("¿no has recibido el correo? verifica la carpeta de ");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 400, 20));

        kGradientPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 470, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
    String codigoIngresado = txtcodigo.getText().trim();

    if (codigoIngresado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingresa el código recibido por correo.", "Código vacío", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (!codigoIngresado.matches("\\d{6}")) {
        JOptionPane.showMessageDialog(this, "El código debe tener exactamente 6 dígitos numéricos.", "Formato incorrecto", JOptionPane.WARNING_MESSAGE);
        return;
    }

    boolean esValido = consulta.validarcodigo(correoIngresado, codigoIngresado);

    if (esValido) {
        JOptionPane.showMessageDialog(this, "¡Código verificado correctamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        NuevaContrasena cambiar = new NuevaContrasena();
        cambiar.setCorreoIngresado(correoIngresado);
        cambiar.setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "El código ingresado no es válido. Verifica e intenta de nuevo.", "Código incorrecto", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
    rSMaterialButtonRectangle2ActionPerformed(null);


    }//GEN-LAST:event_txtcodigoActionPerformed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        Correo_electronico login = new Correo_electronico();
        login.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
   if (correoIngresado == null || correoIngresado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Error: No se ha especificado un correo electrónico válido.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (activeTimer != null && activeTimer.isRunning()) {
        JOptionPane.showMessageDialog(this, "Por favor espera a que finalice el temporizador antes de reenviar el código.", "Espera necesaria", JOptionPane.WARNING_MESSAGE);
        return;
    }

    jLabel6.setEnabled(false);
    jLabelTimer.setVisible(true);
    final int[] countdown = {30};
    jLabelTimer.setText(countdown[0] + "s");

    activeTimer = new Timer(1000, e -> {
        countdown[0]--;
        if (countdown[0] >= 0) {
            jLabelTimer.setText(countdown[0] + "s");
        } else {
            ((Timer) e.getSource()).stop();
            jLabel6.setEnabled(true);
            jLabelTimer.setVisible(false);
            activeTimer = null;
        }
    });
    activeTimer.start();

    try {
        String codigo = consulta.reenviarCodigo(correoIngresado);

        if (codigo != null) {
            JOptionPane.showMessageDialog(this, "El código de recuperación ha sido reenviado correctamente.", "Código reenviado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo reenviar el código. Verifica el correo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar reenviar el código.", "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jLabel6MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Correo_electronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Correo_electronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Correo_electronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Correo_electronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contrasena3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private keeptoo.KGradientPanel kGradientPanel1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSPanelImage rSPanelImage1;
    private javax.swing.JTextField txtcodigo;
    // End of variables declaration//GEN-END:variables

}
