/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

//import controlador.Contrl_login;
import vista.alertas.AlertaUsuarioE;
import vista.alertas.AlertaReestablecerContrasena;
import controlador.Contrl_login;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Consulta_Usuarios;

import vista.alertas.AlertaCambioContraseña;

/**
 *
 * @author Personal
 */
public class NuevaContrasena extends javax.swing.JFrame {

    private String correoIngresado = "";
    private boolean isPasswordVisible = false;
    private boolean isPasswordVisible1 = false; // Para el segundo campo
    private JPanel tooltip; // Para el tooltip

    public void setCorreoIngresado(String correo) {
        this.correoIngresado = correo;
    }



    public NuevaContrasena() {
        initComponents();
        // Enter en la primera contraseña: enfocar la segunda
txtcontrasenanueva.addActionListener(e -> txtcontrasenanueva1.requestFocus());

// Enter en la segunda contraseña: activar botón "Continuar"
txtcontrasenanueva1.addActionListener(e -> iniciar.doClick());

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);

        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.CENTER;
        add(kGradientPanel1, gbc);

        JPanel fondo = new JPanel(new BorderLayout());
        fondo.add(kGradientPanel1, BorderLayout.CENTER);
        setContentPane(fondo);



      

   
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel6 = new javax.swing.JPanel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        iniciar = new RSMaterialComponent.RSButtonShape();
        txtcontrasenanueva = new RSMaterialComponent.RSPasswordIconOne();
        txtcontrasenanueva1 = new RSMaterialComponent.RSPasswordIconOne();
        jLabel12 = new javax.swing.JLabel();
        rSButtonMaterialRippleIcon1 = new RSMaterialComponent.RSButtonMaterialRippleIcon();
        rSButtonMaterialRippleIcon2 = new RSMaterialComponent.RSButtonMaterialRippleIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setBackground(new java.awt.Color(153, 255, 51));
        kGradientPanel1.setForeground(new java.awt.Color(255, 204, 204));
        kGradientPanel1.setkEndColor(new java.awt.Color(239, 248, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(254, 254, 254));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/logo_azul.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel6.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 130, 120));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel11.setText("Cambia tu contraseña");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel7.setText("Confirmar Contraseña:");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 20));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel8.setText("volver al inicio de sesion");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 170, 20));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel9.setText("Escribe tu nueva contraseña, recuerda que debe tener");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 410, 20));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel10.setText("8 digitos");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 410, 20));

        iniciar.setBackground(new java.awt.Color(29, 30, 51));
        iniciar.setText("                                                   Continuar");
        iniciar.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        jPanel6.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 410, 40));

        txtcontrasenanueva.setForeground(new java.awt.Color(0, 0, 0));
        txtcontrasenanueva.setToolTipText("");
        txtcontrasenanueva.setBorderColor(new java.awt.Color(230, 230, 230));
        txtcontrasenanueva.setColorIcon(new java.awt.Color(204, 204, 204));
        txtcontrasenanueva.setPhColor(new java.awt.Color(51, 51, 51));
        txtcontrasenanueva.setPlaceholder("Ingrese su contraseña");
        txtcontrasenanueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontrasenanuevaActionPerformed(evt);
            }
        });
        jPanel6.add(txtcontrasenanueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 390, 40));

        txtcontrasenanueva1.setForeground(new java.awt.Color(0, 0, 0));
        txtcontrasenanueva1.setToolTipText("");
        txtcontrasenanueva1.setBorderColor(new java.awt.Color(230, 230, 230));
        txtcontrasenanueva1.setColorIcon(new java.awt.Color(204, 204, 204));
        txtcontrasenanueva1.setPhColor(new java.awt.Color(51, 51, 51));
        txtcontrasenanueva1.setPlaceholder("Ingrese su contraseña");
        txtcontrasenanueva1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontrasenanueva1ActionPerformed(evt);
            }
        });
        jPanel6.add(txtcontrasenanueva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 390, 40));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel12.setText("Contraseña:");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 20));

        rSButtonMaterialRippleIcon1.setBackground(new java.awt.Color(242, 247, 255));
        rSButtonMaterialRippleIcon1.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonMaterialRippleIcon1.setBackgroundHover(new java.awt.Color(242, 247, 255));
        rSButtonMaterialRippleIcon1.setForegroundHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialRippleIcon1.setForegroundIcon(new java.awt.Color(0, 0, 0));
        rSButtonMaterialRippleIcon1.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialRippleIcon1.setForegroundText(new java.awt.Color(0, 0, 0));
        rSButtonMaterialRippleIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.VISIBILITY);
        rSButtonMaterialRippleIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialRippleIcon1ActionPerformed(evt);
            }
        });
        jPanel6.add(rSButtonMaterialRippleIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 40, 40));

        rSButtonMaterialRippleIcon2.setBackground(new java.awt.Color(242, 247, 255));
        rSButtonMaterialRippleIcon2.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonMaterialRippleIcon2.setBackgroundHover(new java.awt.Color(242, 247, 255));
        rSButtonMaterialRippleIcon2.setForegroundHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialRippleIcon2.setForegroundIcon(new java.awt.Color(0, 0, 0));
        rSButtonMaterialRippleIcon2.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialRippleIcon2.setForegroundText(new java.awt.Color(0, 0, 0));
        rSButtonMaterialRippleIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.VISIBILITY);
        rSButtonMaterialRippleIcon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialRippleIcon2ActionPerformed(evt);
            }
        });
        jPanel6.add(rSButtonMaterialRippleIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 40, 40));

        kGradientPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 470, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
  Login1121 login = new Login1121();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MousePressed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
 String nuevaContrasena = txtcontrasenanueva.getText().trim();
        String confirmarContrasena = txtcontrasenanueva1.getText().trim();

        // Validar campos vacíos
        if (nuevaContrasena.isEmpty() || confirmarContrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete ambos campos de contraseña.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar que coincidan
        if (!nuevaContrasena.equals(confirmarContrasena)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar formato
        String regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$";
        if (!nuevaContrasena.matches(regex)) {
            JOptionPane.showMessageDialog(this,
                    "La contraseña debe tener mínimo 8 caracteres,\nuna mayúscula, una minúscula, un número y un carácter especial.",
                    "Contraseña inválida", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Guardar
        Consulta_Usuarios controlador = new Consulta_Usuarios();
        boolean cambioExitoso = controlador.actualizarContrasena(correoIngresado, nuevaContrasena);

        if (cambioExitoso) {
            JOptionPane.showMessageDialog(this, "¡Contraseña actualizada con éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new Login1121().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Hubo un error al actualizar la contraseña.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_iniciarActionPerformed

    private void txtcontrasenanuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontrasenanuevaActionPerformed

    }//GEN-LAST:event_txtcontrasenanuevaActionPerformed

    private void txtcontrasenanueva1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontrasenanueva1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontrasenanueva1ActionPerformed

    private void rSButtonMaterialRippleIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialRippleIcon1ActionPerformed
 togglePasswordVisibility1();
    }//GEN-LAST:event_rSButtonMaterialRippleIcon1ActionPerformed

    private void rSButtonMaterialRippleIcon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialRippleIcon2ActionPerformed
togglePasswordVisibility();
    }//GEN-LAST:event_rSButtonMaterialRippleIcon2ActionPerformed

    /**
     * @param context
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Correo_electronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Correo_electronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Correo_electronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Correo_electronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonShape iniciar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private keeptoo.KGradientPanel kGradientPanel1;
    private RSMaterialComponent.RSButtonMaterialRippleIcon rSButtonMaterialRippleIcon1;
    private RSMaterialComponent.RSButtonMaterialRippleIcon rSButtonMaterialRippleIcon2;
    private rojerusan.RSPanelImage rSPanelImage1;
    private RSMaterialComponent.RSPasswordIconOne txtcontrasenanueva;
    private RSMaterialComponent.RSPasswordIconOne txtcontrasenanueva1;
    // End of variables declaration//GEN-END:variables


//

    //
    
    // Método para alternar visibilidad de la primera contraseña
private void togglePasswordVisibility() {
    if (isPasswordVisible) {
        txtcontrasenanueva.setEchoChar('*'); // Ocultar con '*'
        rSButtonMaterialRippleIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.VISIBILITY); // Ícono de ojo visible
    } else {
        txtcontrasenanueva.setEchoChar((char) 0); // Mostrar como texto plano
        rSButtonMaterialRippleIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.VISIBILITY_OFF); // Ícono de ojo tachado
    }
    isPasswordVisible = !isPasswordVisible;
}

// Método para alternar visibilidad de la segunda contraseña
private void togglePasswordVisibility1() {
    if (isPasswordVisible1) {
        txtcontrasenanueva1.setEchoChar('*'); // Ocultar con '*'
        rSButtonMaterialRippleIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.VISIBILITY); // Ícono de ojo visible
    } else {
        txtcontrasenanueva1.setEchoChar((char) 0); // Mostrar como texto plano
        rSButtonMaterialRippleIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.VISIBILITY_OFF); // Ícono de ojo tachado
    }
    isPasswordVisible1 = !isPasswordVisible1;
}
}
